version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    restart: always
    env_file:
      - ./api/.env
    command: ["./api"]

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./admin/.env

    restart: always
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "python manage.py makemigration && pyhon manage.py migrate && python manage.py runserver"