version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    command: "./api"

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./admin/.env
    volumes:
      - ./admin:/app

    restart: always
    command: sh -c "python manage.py runserver 0.0.0.0:8000"